AnonymousZB14/USports_BE

- src/main/java/com/anonymous/usports/domain/participant/controller/ParticipantController.java
- src/main/java/com/anonymous/usports/domain/participant/dto/ParticipantListDto.java
- src/main/java/com/anonymous/usports/domain/participant/dto/ParticipateCancel.java
- src/main/java/com/anonymous/usports/domain/participant/entity/ParticipantEntity.java
- src/main/java/com/anonymous/usports/domain/participant/repository/ParticipantRepository.java
- src/main/java/com/anonymous/usports/domain/participant/service/ParticipantService.java
- src/main/java/com/anonymous/usports/domain/participant/service/impl/ParticipantServiceImpl.java
- src/main/java/com/anonymous/usports/domain/recruit/controller/RecruitController.java
- src/main/java/com/anonymous/usports/domain/recruit/entity/RecruitEntity.java
- src/main/java/com/anonymous/usports/domain/recruit/service/impl/RecruitServiceImpl.java
- src/main/java/com/anonymous/usports/global/constant/ResponseConstant.java
- src/main/java/com/anonymous/usports/global/exception/MyExceptionHandler.java
- src/main/java/com/anonymous/usports/global/exception/ParticipantException.java
- src/main/java/com/anonymous/usports/global/exception/RecruitException.java
- src/main/java/com/anonymous/usports/global/exception/SportsException.java
- src/test/java/com/anonymous/usports/domain/participant/service/ParticipantServiceTest.java
- src/test/java/com/anonymous/usports/domain/recruit/service/RecruitServiceTest.java
**[모집글 참여 신청 취소]**
- ING / ACCEPTED 상태를 순차적으로 찾는다.
- 둘중 하나라도 먼저 찾으면 해당 신청 내역을 삭제한다.
- 참여 신청은 ING, ACCEPTED, REFUSED로 나눠지는데, ING 와 ACCEPTED는 하나만 존재할 수 있기 때문이다.
**[테스트]**
아래 세 개의 리뷰를 받았다.
- 테스트 케이스는 모든 예외상황까지 테스트를 해야지 의미가 있다.
- any(), anyLong() 등은 사용하지 않는게 좋다.
- 테스트를 위한 엔티티에 같은 값을 넣지 마라 ( title = "test", content = "test", name = "test" 처럼 같은 값을 대충 넣는 것)
이에 따라 ParticipantService, RecruitService의 모든 메서드의 모든 예외 사항에 대한 테스트 코드를 작성하였다.
- @BeforeEach에서 엔티티를 생성하여 static field에 저장하는 방식보다 private 메서드로 엔티티를 생성하는 방식이 더 효율적이라고 판단하여 수정하였다.
**[entity register 시 문제 발생]**
처음으로 엔티티를 등록하는 경우, request.toEntity()의 주소와, save 메서드 실행 후 반환되는 엔티티의 주소가 달라서 문제가 발생했다.
- Entity class에 @EqualsAndHashcode를 추가하여 해결하였다.
- 이 어노테이션은 조금 더 조심히 다뤄야 하기 때문에 추후에(빠른 시일 내로) 해당 내용 공부 후 직접 구현하는 방식으로 수정 할 예정이다.
> 모집글 참여 신청 취소 기능 구현, RecruitService, ParticipantService 테스트 코드 추가, 리팩터링

- src/main/java/com/anonymous/usports/domain/participant/dto/ParticipantListDto.java
- src/main/java/com/anonymous/usports/domain/participant/service/impl/ParticipantServiceImpl.java
- src/main/java/com/anonymous/usports/domain/recruit/controller/RecruitController.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitDto.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitRegister.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitSearchListDto.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitUpdate.java
- src/main/java/com/anonymous/usports/domain/recruit/entity/RecruitEntity.java
- src/main/java/com/anonymous/usports/domain/recruit/repository/RecruitRepository.java
- src/main/java/com/anonymous/usports/domain/recruit/service/RecruitService.java
- src/main/java/com/anonymous/usports/domain/recruit/service/impl/RecruitServiceImpl.java
- src/main/java/com/anonymous/usports/domain/sports/repository/SportsRepository.java
- src/main/resources/application.properties
- src/test/java/com/anonymous/usports/domain/participant/service/ParticipantServiceTest.java
- src/test/java/com/anonymous/usports/domain/recruit/service/RecruitServiceTest.java
**[게시글 필터링 구현(조건 별 검색)]**
- 게시글을 필터링하여 Page<RecruitEntity>를 반환하는 것 까지 완료
- JPQL(@Query)을 이용해서 각 검색 조건들이 null인 경우 처리
- "마감 글 포함" 항목은 따로 구분이 어려워서 해당 조건을 기준으로 두개의 Repository로 분리
(주의)
- String은 request가 들어올 때 null이 아니라 ""가 들어오는 경우도 있기 때문에 Strings.hasText()로 구분할 것
- Repository에서는 null인 경우에 제외하도록 했기 때문에 주의해야 함
**[게시글 필터링 구현완료]**
- 위에서 받은 Page<RecruitEntity>를 원하는 형식의 DTO로 변환
- 프론트에서 필요한 부분은 아래와 같음
- 현재 페이지 
- 현재 페이지의 데이터 개수 
- 전체 데이터 개수
- 전체 페이지 개수
- 한 페이지의 크기(필수는 아닌 것 같음) 
- 모두 Page<>에서 얻을 수 있는 데이터
- 추가로 이전에 만들었던 ParticipantListDto도 이번에 만든 RecruitSearchListDto와 형식을 맞춤
**[테스트코드 작성]**
- 이 메서드에 대한 테스트는 아무래도 mocking을 이용한 단위 테스트로는 검증이 어렵다고 생각됨.
- 통합 테스트를 고려해볼 만 하다.
> 운동 모집 게시글 검색 기능 구현, 테스트

- src/main/java/com/anonymous/usports/domain/member/security/JwtAuthenticationFilter.java
**AS-IS**
[access token 사용 여부]
로그아웃을 진행했을 때에 access token을 redis에 넣는 것까지 완성.
다시 복습을 해보니, access token이 redis에 있을 때에, 어떻게 하면 해당 토큰이 만료됬을 때까지 사용을 할 수 없게 만들 수 있는지 고민하게 됨.
JwtAuthenticationFilter 클래스에서 토큰을 인증 할 때에, redis에 들어가서 해당 토큰이 존재하는지 확인하는 코드를 if문에 추가만 했음!
> FEAT : doFilterInternal 안에 if문에 access tokenì의 블랙리스트 여부 확인 추가

- src/main/java/com/anonymous/usports/domain/follow/controller/FollowController.java
- src/main/java/com/anonymous/usports/domain/follow/entity/FollowEntity.java
- src/main/java/com/anonymous/usports/domain/follow/service/FollowService.java
- src/main/java/com/anonymous/usports/domain/follow/service/impl/FollowServiceImpl.java
- src/main/java/com/anonymous/usports/global/exception/ErrorCode.java
- src/test/java/com/anonymous/usports/domain/follow/service/impl/FollowServiceImplTest.java
**AS-IS**
**[Follow 부분 테스트 코드 추가]**
- follow 부분 테스트 코드를 추가했습니다.
**[changeFollow 부분 예외 상황 추가]**
- API 테스트 때 자기 자신을 팔로우하는 것이 필터링이 되지 않는다는 것을 알게 되어서 추가했습니다.(SELF_FOLLOW_NOT_ALLOWED)
**[manageFollow 부분 예외 상황 제거]**
- 제작 초기에는 followId를 넘겨서 그걸 통해 수정했기 때문에 권한이 없는 경우 발생하는 에러(NO_AUTHORITY_ERROR)가 존재했습니다. 
현재는 그 이전에 FOLLOW_NOT_FOUND에서 걸러지기 때문에 NO_AUTHORITY_ERROR가 발생할 수 없음을 확인했습니다.
따라서 NO_AUTHORITY_ERROR를 제거하였습니다.
**[@AuthenticationPrincipal을 사용하는 member의 이름을 loginMember로 변경]**
- @AuthenticationPrincipal을 사용하는 member의 이름을 loginMember로 변경했습니다.
---
커밋을 따로 해서 별도 PR로 올려야 했는데 테스트 코드 작성하면서 눈에 들어오는 부분을 바로 수정하다보니 부득이하게 수정사항과 테스트코드 내용을 합쳐서 올리게 되었습니다.
다음부터는 커밋과 PR 관련 규칙을 준수하겠습니다!
---
**TO-BE**
- 기록 관련 테스트코드 작성
- 기록 좋아요 기능
- 기록 댓글, 대댓글 기능
- [] API 테스트
> Test: Follow 부분 테스트 코드 추가

- build.gradle
- src/main/java/com/anonymous/usports/domain/recruit/api/component/AddressConverter.java
- src/main/java/com/anonymous/usports/domain/recruit/api/dto/Address.java
- src/main/java/com/anonymous/usports/domain/recruit/api/dto/AddressDto.java
- src/main/java/com/anonymous/usports/domain/recruit/api/dto/AddressResponse.java
- src/main/java/com/anonymous/usports/domain/recruit/api/dto/Document.java
- src/main/java/com/anonymous/usports/domain/recruit/api/dto/Meta.java
- src/main/java/com/anonymous/usports/domain/recruit/api/dto/RoadAddress.java
- src/main/java/com/anonymous/usports/global/exception/ErrorCode.java
- src/test/java/com/anonymous/usports/test/AddressConverterApiTest.java
FE 에서 다음 주소 API를 이용해 정확한 도로명 주소  String을 받는다. 
받은 문자열 roadNameAddress 를 
AddressConverter.roadNameAddressToLocationInfo(String roadNameAddress) 에 인수로 넣으면 
자세한 위치 정보 (건물코드, 위도, 경도 등)을 얻을 수 있음.
- AddressDto : AddressResponse중 필요한 부분만을 추출한 Dto , 이 Dto를 다른 서비스에서 사용할 예정
- AddressResponse : 최상위 객체
- Meta : 메타 데이터
- Document 
- address_name : 전체 지번 주소 또는 도로명 주소
- address_type : 주소 type (REGION, ROAD, REGION_ADDR, ROAD_ADDR)
- x : lnt(경도)
- y : lat(위도)
- address : 주소 객체
- roadAddress : 도로명 주소 상세 정보
> Kakao 주소 API > 주소 검색하기

- src/main/java/com/anonymous/usports/domain/RecordLike/controller/RecordLikeController.java
- src/main/java/com/anonymous/usports/domain/RecordLike/dto/RecordLikeDto.java
- src/main/java/com/anonymous/usports/domain/RecordLike/entity/RecordLikeEntity.java
- src/main/java/com/anonymous/usports/domain/RecordLike/repository/RecordLikeRepository.java
- src/main/java/com/anonymous/usports/domain/RecordLike/service/RecordLikeService.java
- src/main/java/com/anonymous/usports/domain/RecordLike/service/impl/RecordLikeServiceImpl.java
- src/main/java/com/anonymous/usports/domain/record/entity/RecordEntity.java
- src/main/java/com/anonymous/usports/global/constant/ResponseConstant.java
- src/main/java/com/anonymous/usports/global/exception/ErrorCode.java
- src/test/java/com/anonymous/usports/domain/RecordLike/service/impl/RecordLikeServiceImplTest.java
**기록에 대한 좋아요 신청/취소 기능**
기존에 등록된 기록에 대한 '좋아요' 기능을 추가했습니다.
기존에 '좋아요' 정보가 있을 시 기존 정보를 삭제하는 방식으로 취소가 작동합니다.
recordEntity에 countRecordLikes 항목을 추가하여 '좋아요'가 등록될 시 +1, 취소될 시 -1이 됩니다.
자기 자신의 기록에 대한 '좋아요' 신청은 거절됩니다.
Postman으로 진행했으며 회원 1,2와 record 1을 생성하여 진행했습니다.
- 없는 기록 Id로 '좋아요' 요청이 들어왔을 때 RECORD_NOT_FOUND 확인
- 자기 자신의 기록에 대한 '좋아요' 신청 시 SELF_LIKE_NOT_ALLOWED 확인
- 기존 '좋아요' 정보가 없을 경우 DB에 '좋아요' 정보가 입력되는 것을 확인('좋아요' 신청)
- 기존 '좋아요' 정보가 있을 경우 DB에 기존 '좋아요' 정보가 삭제되는 것을 확인('좋아요' 취소)
- '좋아요' 신청과 취소 시 record의 count_recordlike 항목이 각각 +1 / -1되는 것을 확인
> Feat: 기록에 대한 좋아요 기능 추가

- src/main/java/com/anonymous/usports/domain/RecordLike/service/RecordLikeService.java
- src/main/java/com/anonymous/usports/domain/recordlike/controller/RecordLikeController.java
- src/main/java/com/anonymous/usports/domain/recordlike/dto/RecordLikeDto.java
- src/main/java/com/anonymous/usports/domain/recordlike/entity/RecordLikeEntity.java
- src/main/java/com/anonymous/usports/domain/recordlike/repository/RecordLikeRepository.java
- src/main/java/com/anonymous/usports/domain/recordlike/service/RecordLikeService.java
- src/main/java/com/anonymous/usports/domain/recordlike/service/impl/RecordLikeServiceImpl.java
- src/test/java/com/anonymous/usports/domain/recordlike/service/impl/RecordLikeServiceImplTest.java
**AS-IS**
오전에 코멘트 받았던 사항들 수정했습니다. 
이 부분은 앞서 있었던 PR과 비교해서 명칭 제외 크게 바뀐 부분이 없으므로 구체적인 테스트 설명은 생략하겠습니다.
- switchLike 명칭 switchLikeOrCancel로 변경
- 엔티티명 recordlike에서 record_like로 변경
- findByRecordAndMember RecordLikeEntity에서 Optional<RecordLikeEntity>로 변경
- 패키지 RecordLike에서 recordlike로 변경
**TO-BE**
> Refactor: RecordLike 관련 리팩토링

- src/main/java/com/anonymous/usports/domain/member/repository/MemberRepository.java
- src/main/java/com/anonymous/usports/domain/member/security/SecurityConfig.java
- src/main/java/com/anonymous/usports/domain/mypage/controller/MyPageController.java
- src/main/java/com/anonymous/usports/domain/mypage/service/MyPageService.java
- src/main/java/com/anonymous/usports/domain/mypage/service/impl/MyPageServiceImpl.java
- src/main/java/com/anonymous/usports/domain/participant/repository/ParticipantRepository.java
- src/main/java/com/anonymous/usports/domain/profile/controller/ProfileController.java
- src/main/java/com/anonymous/usports/domain/profile/dto/ProfileRecords.java
- src/main/java/com/anonymous/usports/domain/profile/dto/ProfileRecruits.java
- src/main/java/com/anonymous/usports/domain/profile/service/ProfileService.java
- src/main/java/com/anonymous/usports/domain/profile/service/impl/ProfileServiceImpl.java
- src/main/java/com/anonymous/usports/domain/record/dto/RecordListDto.java
- src/main/java/com/anonymous/usports/domain/record/repository/RecordRepository.java
- src/main/java/com/anonymous/usports/domain/recruit/controller/RecruitController.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitListDto.java
- src/main/java/com/anonymous/usports/domain/recruit/service/RecruitService.java
- src/main/java/com/anonymous/usports/domain/recruit/service/impl/RecruitServiceImpl.java
- src/main/java/com/anonymous/usports/global/constant/NumberConstant.java
- src/test/java/com/anonymous/usports/domain/recruit/service/RecruitServiceTest.java
Profile 페이지의 Record, Recruit 를 각각 구현했습니다.
두 페이지 모두 
- MyPageMember 데이터
- SportsSkills  
가 필요합니다. 
MyPageService에서 위의 두가지 데이터를 불러오는 부분 메서드를 그대로 사용했습니다.
각 페이지에는 위의 두가지 데이터가 공통으로 포함되고
Record 페이지에는 멤버의 Record가 최신순으로,
Recruit 페이지에는 멤버의 마감된 Recruit가 최신순으로 정렬되어 반환됩니다.
**[테스트]**
API 테스트를 진행했습니다.
테스트코드는 각 List를 불러오는 부분을 제외하고는 MyPageService Test에서 수행했기 때문에 생략했습니다.
> Profile page

- src/main/java/com/anonymous/usports/domain/member/controller/MemberContoller.java
- src/main/java/com/anonymous/usports/domain/member/dto/MemberLogin.java
- src/main/java/com/anonymous/usports/domain/participant/dto/ParticipantDto.java
- src/main/java/com/anonymous/usports/domain/participant/entity/ParticipantEntity.java
- src/main/java/com/anonymous/usports/domain/participant/service/impl/ParticipantServiceImpl.java
- src/main/java/com/anonymous/usports/domain/recruit/controller/RecruitController.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitRegister.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitResponse.java
- src/main/java/com/anonymous/usports/domain/recruit/service/RecruitService.java
- src/main/java/com/anonymous/usports/domain/recruit/service/impl/RecruitServiceImpl.java
- src/main/java/com/anonymous/usports/domain/sportsskill/entity/SportsSkillEntity.java
- src/main/java/com/anonymous/usports/global/exception/ErrorCode.java
- src/main/java/com/anonymous/usports/global/type/Gender.java
- src/main/java/com/anonymous/usports/global/type/RecruitStatus.java
- src/main/java/com/anonymous/usports/global/type/SportsGrade.java
- src/test/java/com/anonymous/usports/domain/participant/service/ParticipantServiceTest.java
- src/test/java/com/anonymous/usports/domain/recruit/service/RecruitServiceTest.java
**[테스트 코드 수정]**
- 이전에 테스트코드 수정 안한 부분만 수정했습니다.
**[Recruit GET DTO 변경]**
- SportsGrade와 같은 데이터들 반환할 때 description에 있는 String으로 반환해달라는 요청을 받고 수정했습니다.
- 클라이언트에 Response를 보낼 때 ENUM을 사용자에게 보여주기 위한 String으로 수정해서 보내야합니다.
- 몇가지 ENUM 클래스에 description 을 추가하고, 이를 변환하는 메서드를 만들어두었습니다.
**[Recruit 생성 시 host를 참여자로 추가]**
- Recruit 생성시에 host(모집글 등록 자)를 첫번째 Participant로 추가하도록 수정했습니다.
**[Participant 생성 시 SportsSkill 정보 추가]**
- ParticipantEntity에 sportsSkill 필드와 DB에 컬럼을 추가하였습니다.
- 참여 신청 시 사용자의 운동 능력 정보를 볼 수 있게 하기 위함입니다.
- 추가로 SportsSkill 기록이 없는 경우 0.0으로 설정하여, 사용자에게 ROOKIE 상태로 반환되게 됩니다.
**[로그인 시 Member 정보추가]**
- 로그인 시 TokenDto만 반환하던 것에서 MemberDto 정보도 추가로 반환하도록 수정
> Refactor/Fix : Response 데이터타입 수정, Recruit 생성 시 문제 수정

- docker-compose.yml
- src/main/resources/templates/chat/room.html
**AS-IS**
- docker compose 파일 수정해서 docker에 rabbitMQ 설치 시 필요한 플러그인들이 같이 설치되도록 변경했습니다.
- 기존에는 reconnect 시 sendEnterMessage가 계속 작동하여 sendEnterMessage의 위치를 변경했습니다.
**TO-BE**
> Refactor: rabbitMQ 플러그인 설치 관련 docker-compose 수정

- src/main/java/com/anonymous/usports/domain/member/controller/MemberContoller.java
- src/main/java/com/anonymous/usports/domain/member/dto/MemberLogin.java
- src/main/java/com/anonymous/usports/domain/mypage/controller/MyPageController.java
- src/main/java/com/anonymous/usports/domain/mypage/service/MyPageService.java
- src/main/java/com/anonymous/usports/domain/mypage/service/impl/MyPageServiceImpl.java
- src/main/java/com/anonymous/usports/domain/profile/service/impl/ProfileServiceImpl.java
- src/test/java/com/anonymous/usports/domain/mypage/service/MyPageServiceTest.java
Login 시에 로그인 회원의 InterestSportsList를 추가로 반환하도록 수정
**[MyPageService.getMyPageMember 수정]**
- getMyPageMember에서 InterestSportsList를 불러오던 부분을 메서드 분리하여 Member 로그인시 사용할 수 있도록 수정
- getMyPageMember에서 랜덤한 3개의 Sports를 뽑아내던 로직 수정 
- 기존은 중복으로 뽑힐 여지가 있었다고 생각
- Collections.shuffle() 메서드 이용한 뒤, 맨 앞의 3개 반환
**[회원 로그인 시 interestSportsList 추가 반환]** 
- 위에서 분리한 메서드 `getInterestSportsList(Long memberId)`를 호출하여 응답에 추가함
> Refactor : Login시에 회원의 interestSportsList 추가로 반환하도록 수정

- src/main/java/com/anonymous/usports/domain/member/controller/MemberController.java
- src/main/java/com/anonymous/usports/domain/member/dto/MemberLogin.java
- src/main/java/com/anonymous/usports/domain/member/dto/MemberUpdate.java
- src/main/java/com/anonymous/usports/domain/member/service/impl/MemberServiceImpl.java
- src/main/java/com/anonymous/usports/domain/mypage/dto/MemberInfo.java
- src/main/java/com/anonymous/usports/domain/mypage/service/MyPageService.java
- src/main/java/com/anonymous/usports/domain/mypage/service/impl/MyPageServiceImpl.java
- src/test/java/com/anonymous/usports/domain/member/controller/MemberControllerTest.java
- src/test/java/com/anonymous/usports/domain/member/service/MemberServiceTest.java
- src/test/java/com/anonymous/usports/domain/mypage/service/MyPageServiceTest.java
**[MyPageService.getInterestedSportsList 변경 사항]**
(전)
- 관심 운동 List는 무조건 3개 이하 랜덤으로 뽑아서 주고, 나머지는 plusAlpha라는 데이터로 보냄  
- ex) ListSize = 5일 때 , 3개 랜덤으로 뽑아서 size=3인 List와 plusAlpha=2 반환 
(후)
- 관심 운동 List 개수에 상관없이 전부를 담은 List를 반환
- 랜덤 3개와 plusAlpha 또는 "none"은 FE 단에서 처리하도록 수정
**[회원 로그인, 회원 정보 수정 변경 사항]** (두번째 커밋에 실수로 포함됨)
- 회원 정보 수정 - 관심 운동 종목 LIst 삭제 후 저장 하는 로직 수정
- 반환 값을 List<SportsDto>로 수정
- 운동 종목 List, 관심 운동 종목 List는 앞으로 모든 응답을 `List<SportsDto>`로 보내기로 결정
- 운동 종목 List 변수명 : `sportsList`로 고정
- 관심 운동 종목 List 변수명 : `interestedSportsList`로 고정 (interestSportsList x)  
**[MemberControllerTest 변경 사항]**
- `@MockBean` -> `CookieService`, `MyPageService`, `NotificationService` 추가
- MemberControllerTest 실패하던 것 Fix
> Feature/refactor sports List format 수정

- src/main/java/com/anonymous/usports/domain/customerservice/controller/CsController.java
- src/main/java/com/anonymous/usports/domain/customerservice/dto/ChangeStatusDto.java
- src/main/java/com/anonymous/usports/domain/customerservice/dto/CsDto.java
- src/main/java/com/anonymous/usports/domain/customerservice/dto/CsListDto.java
- src/main/java/com/anonymous/usports/domain/customerservice/dto/DeleteCS.java
- src/main/java/com/anonymous/usports/domain/customerservice/dto/RegisterCS.java
- src/main/java/com/anonymous/usports/domain/customerservice/dto/UpdateCS.java
- src/main/java/com/anonymous/usports/domain/customerservice/entity/CsEntity.java
- src/main/java/com/anonymous/usports/domain/customerservice/repository/CsRepository.java
- src/main/java/com/anonymous/usports/domain/customerservice/service/CsService.java
- src/main/java/com/anonymous/usports/domain/customerservice/service/impl/CsServiceImpl.java
- src/main/java/com/anonymous/usports/domain/member/controller/MemberController.java
- src/main/java/com/anonymous/usports/domain/member/security/CustomAuthenticationEntryPoint.java
- src/main/java/com/anonymous/usports/domain/member/security/SecurityConfig.java
- src/main/java/com/anonymous/usports/domain/member/security/handler/CustomAccessDeniedHandler.java
- src/main/java/com/anonymous/usports/global/constant/CsConstant.java
- src/main/java/com/anonymous/usports/global/exception/CsException.java
- src/main/java/com/anonymous/usports/global/exception/ErrorCode.java
- src/main/java/com/anonymous/usports/global/exception/GlobalExceptionHandler.java
- src/main/java/com/anonymous/usports/global/type/CsStatus.java
- src/test/java/com/anonymous/usports/domain/customerservice/service/impl/CsServiceImplTest.java
- src/test/java/com/anonymous/usports/domain/member/controller/MemberControllerTest.java
**AS-IS**
***[신고 등록]***
http://localhost:8080/cs/register
USER 또는 ADMIN이 신고를 할 수 있음
Controller에서 유저 권한을 확인 후, registerCs DTO를 통해서 요청 값을 서버에 넘긴다.
요청 값이 모두 작성이 되야, DB에 저장이 된다
**테스트**
- 신고 등록 성공 테스트 - USER 권한을 가진 유저가 신고를 등록할 때
- 신고 등록 성공 테스트 - ADMIN 권한을 가진 유저가 신고를 등록할 때
- 신고 등록 실패 테스트 - UNAUTH 권한을 가진 유저가 신고를 등록하려고 할 때
***[신고 삭제]***
[http://localhost:8080/cs/delete/{cs_id}](http://localhost:8080/cs/delete/%7Bcs_id%7D)
USER는 자신의 글만 삭제할 수 있다
ADMIN은 모든 글을 삭제할 수 있다 (부적절한 글이 있을 경우)
PathVariable로 글 ID를 받아서, 해당 글을 삭제하는 것
**********테스트**********
- 신고 삭제 성공 테스트 - USER 권한을 가진 유저가 자신의 신고를 삭제할 때
- 신고 삭제 성공 테스트 - ADMIN 권한을 가진 유저가 다른 신고를 삭제할 때 + 자신의 신고를 삭제할 때
- 신고 실패 테스트 - USER 권한을 가진 유저가 다른 신고를 삭제할 때
- 신고 실패 테스트 - 다른 권한을 가진 유저가 신고를 삭제하려고 할
***[신고 수정]*** …
> customer service

- src/main/java/com/anonymous/usports/domain/profile/controller/ProfileController.java
- src/main/java/com/anonymous/usports/domain/profile/dto/MemberProfile.java
- src/main/java/com/anonymous/usports/domain/profile/service/ProfileService.java
- src/main/java/com/anonymous/usports/domain/profile/service/impl/ProfileServiceImpl.java
타인의 프로필 화면에서 팔로우 여부가 필요하기 때문에 팔로우 상태 정보를 포함시키게 되었습니다.
반환되는 MemberProfile에 followStatus 값을 추가했습니다. 
만약 follow가 아닐 경우 null로 반환되며, 
follow 신청은 했지만 아직 수락or거절 되지 않은 경우 'WAITING',
follow 상태인 경우 'ACTIVE'가 반환됩니다.
follow 상태가 아닌 경우 null이 출력되는 것을 확인하였고, follow 상태에서 ACTIVE 출력을 확인했습니다.
> Refactor: 프로필 - 회원 정보에서 팔로우 상태 정보 포함

- src/main/java/com/anonymous/usports/domain/comment/repository/CommentRepository.java
- src/main/java/com/anonymous/usports/domain/profile/controller/ProfileController.java
- src/main/java/com/anonymous/usports/domain/profile/service/ProfileService.java
- src/main/java/com/anonymous/usports/domain/profile/service/impl/ProfileServiceImpl.java
- src/main/java/com/anonymous/usports/domain/record/service/impl/RecordServiceImpl.java
- src/main/java/com/anonymous/usports/domain/recordlike/repository/RecordLikeRepository.java
<br>
***['프로필 - 회원정보' 메서드 이름 변경]***
ProfileController에 profileRecruits가 2개여서 '프로필 - 회원정보' 메서드의 명칭을 profileMember로 수정했습니다.
<br>
<br>
***[profileMember에서 MemberDto 대신 MemberId 값을 넘기도록 수정]***
기존에 MemberDto 자체를 넘겼으나 Long 값인 MemberId를 넘기는 것으로 수정했습니다.
<br>
<br>
***[deleteRecord 부분에 Comment와 RecordLike를 삭제하는 부분 추가]***
deleteRecord 부분에 Comment와 RecordLike를 삭제하는 부분이 누락되어서 추가했습니다.
<br>
<br>
***[API 테스트]***
Record에 댓글과 대댓글, 좋아요를 추가한 후 삭제 기능이 정상적으로 작동함을 확인했습니다.
> Refactor: DeleteRecord 와 profileMember 관련 리팩토링

- src/main/java/com/anonymous/usports/domain/record/dto/RecordDto.java
- src/main/java/com/anonymous/usports/domain/record/service/impl/RecordServiceImpl.java
- src/test/java/com/anonymous/usports/domain/chatroom/service/ChatRoomServiceImplTest.java
**AS-IS**
**[RecordDto에 countRecordLike 추가했습니다.]**
DB에는 기존에 있었으나 RecordDto에 누락되었던 countRecordLike를 추가했습니다.
**[RecordDto에 fromEntityInclueComment 네이밍 변경]**
fromEntityInclueComment 에 오타가 있어 fromEntityIncludeComment로 변경했습니다.
**[ChattingRoomServiceTest 수정]**
getChattingRoomList에서 읽지 않은 채팅 수를 가져오는 부분을 추가했는데 해당 부분에 대한 테스트 코드를 수정하지 않았던 부분을 추가했습니다. 
**TO-BE**
> Refactor: Dto 누락 및 네이밍 수정, Test 코드 수정

- src/main/java/com/anonymous/usports/domain/mypage/dto/MemberInfo.java
**AS-IS**
**[MemberInfo Dto에 profileOpen 값을 추가]**
프로필 등에서 회원 정보를 가져올 때 사용되는 MemberInfo에 프로필 공개 여부를 알 수 있도록 profileOpen을 추가했습니다.
**TO-BE**
> Refactor: MemberInfo에 profileOpen 여부 추가

- src/main/java/com/anonymous/usports/global/constant/TokenConstant.java
- src/main/java/com/anonymous/usports/global/redis/token/repository/RefreshTokenRepository.java
**AS-IS**
**[addBlackListAccessToken 수정]**
AccessToken blacklist에 TTL 값 설정하는 부분에 Duration.ofMillis()를 추가했습니다.
**[REFRESH_TOKEN_VALID_TIME 값 수정]**
기존 refreshToken의 TTL이 5분 정도로 짧았기 때문에 refreshToken의 유효 시간을 3 * 24 * 60 * 60 * 1000L(3일) 로 연장했습니다.
**TO-BE**
> Refactor: accessToken blacklist 수정

- src/main/java/com/anonymous/usports/domain/follow/repository/FollowRepository.java
- src/main/java/com/anonymous/usports/domain/follow/service/impl/FollowServiceImpl.java
- src/main/java/com/anonymous/usports/global/constant/ResponseConstant.java
- src/test/java/com/anonymous/usports/domain/follow/service/impl/FollowServiceImplTest.java
**AS-IS**
**[Follow 신청 시 Waiting 상태 고려]**
기존 follow 신청 시 ACTIVE 상태만 고려해서 취소가 이루어졌다면 이번 수정을 통해 Waiting 상태인 경우의 취소도 추가되었습니다.
기존에 경우에 Waiting 상태를 고려하지 못해 Waiting 인 신청이 있을 경우 계속 follow 신청 버튼을 누르면 새로운 follow가 생겨서 오류가 발생하였습니다.
이번 수정을 통해 그러한 오류의 발생을 막을 수 있을 것입니다.
**TO-BE**
> Refactor: Follow 신청 시 Waiting 상태 고려

- src/main/java/com/anonymous/usports/domain/follow/controller/FollowController.java
- src/main/java/com/anonymous/usports/domain/follow/service/FollowService.java
- src/main/java/com/anonymous/usports/domain/follow/service/impl/FollowServiceImpl.java
- src/main/java/com/anonymous/usports/domain/record/dto/RecordDto.java
- src/main/java/com/anonymous/usports/domain/record/dto/RecordRegister.java
- src/main/java/com/anonymous/usports/domain/record/entity/RecordEntity.java
- src/main/java/com/anonymous/usports/domain/record/service/impl/RecordServiceImpl.java
- src/main/java/com/anonymous/usports/global/constant/ChatConstant.java
- src/main/java/com/anonymous/usports/global/type/FollowListType.java
- src/main/java/com/anonymous/usports/websocket/controller/ChatPartakeController.java
- src/main/java/com/anonymous/usports/websocket/controller/ChatRoomController.java
- src/main/java/com/anonymous/usports/websocket/dto/ChatMessageListDto.java
- src/main/java/com/anonymous/usports/websocket/repository/ChattingRepository.java
- src/main/java/com/anonymous/usports/websocket/service/ChatRoomService.java
- src/main/java/com/anonymous/usports/websocket/service/impl/ChatRoomServiceImpl.java
- src/test/java/com/anonymous/usports/domain/follow/service/impl/FollowServiceImplTest.java
기존 List<ChatMessageDto>로 불러오던 채팅 내역을 100개씩 페이징 처리하여 불러오도록 수정했습니다.
AWS Lambda를 이용해서 사진이 버킷에 업로드 될 때 섬네일 전용 버킷에 이미지가 리사이징 되어 저장됩니다.
(Lambda를 사용했기 때문에 코드 상에서 리사이징 하는 부분은 없습니다.)
따라서 DB에 섬네일 URL을 저장 할 필요성이 생겼습니다. 
섬네일 관련 thImageAddress 항목이 엔티티에 추가되었고, Dto에도 thImageAddressList 항목이 추가되었습니다.
원본 이미지 URL을  DB에 저장 시 섬네일 URL도 같이 저장됩니다.
기록글 수정 시 이미지에 수정이 발생하면 섬네일URL도 수정하는 부분이 추가되었습니다.
기존 FollowList는 한 개의 API에서 FollowType 별로 Following, Follower, RequestedFollow 3개의 타입으로 list를 받아오는 방식이였습니다.
해당 회원 본인이 아닌 다른 회원도 그 회원이 누구를 팔로우 하는지 볼 수 있어야 한다는 의견이 있었기에 회원 당사자가 아니더라도 누구를 팔로우하고 누가 그 회원을 팔로우 하는지 리스트를 볼 수 있도록 변경되었습니다.
해당 회원에게 온 팔로우 신청은 아예 getRequestedFollowList 라는 별도 API로 구현하였습니다.
이러한 변화에 따라 FollowType도 Follower와 Following, 2개로 변경되었습니다.
기존 테스트 코드를 수정했고 getRequestedFollowList 에 대한 테스트 코드가 추가되었습니다.
markChatAsRead …
> Refactor: 채팅 내역 페이징 처리 및 기록 섬네일 작업

- src/main/java/com/anonymous/usports/websocket/controller/ChatPartakeController.java
- src/main/java/com/anonymous/usports/websocket/service/impl/ChatPartakeServiceImpl.java
**AS-IS**
[ChatPartakeController를 Swagger 어노테이션 추가]
ChatPartakeController 에 있는 markChatAsRead 에 ApiOperation 어노테이션 추가했습니다.
[ChatPartakeServiceImpl에 주석 추가]
markChatAsRead 메서드를 설명하는 주석을 추가했습니다.
**TO-BE**
> Refactor: ChatPartake Swagger 추가 및 주석 추가

- src/main/java/com/anonymous/usports/websocket/dto/ChatMessageListDto.java
- src/main/java/com/anonymous/usports/websocket/service/impl/ChatRoomServiceImpl.java
**AS-IS**
[messagelist 관련 코드 수정]
기존에는 senderMember에 채팅 보낸 회원이 아닌 접속한 회원을 넣는 실수를 했기에 코드를 수정합니다.
채팅방에 참여한 MemberEntity의 List를 가져와서 회원ID가 동일한 MemberEntity의 정보를 사용합니다.
**TO-BE**
> Refactor: MessageList 관련 코드 수정

- src/main/java/com/anonymous/usports/global/constant/ChatConstant.java
- src/main/java/com/anonymous/usports/global/exception/ErrorCode.java
- src/main/java/com/anonymous/usports/websocket/controller/ChatRoomController.java
- src/main/java/com/anonymous/usports/websocket/dto/ChatResponses/ChatEnterDto.java
- src/main/java/com/anonymous/usports/websocket/service/ChatRoomService.java
- src/main/java/com/anonymous/usports/websocket/service/impl/ChatPartakeServiceImpl.java
- src/main/java/com/anonymous/usports/websocket/service/impl/ChatRoomServiceImpl.java
- src/test/java/com/anonymous/usports/domain/record/service/impl/RecordServiceImplTest.java
recruit에서 참여자의 상태가 ACCEPTED이면서 채팅방에 참여하지 않은 사람들의 리스트를 출력합니다.
기존에는 가져올 ChattingEntity가 없을 경우 해당 부분(chattingEntity.getId().toString())에서 문제가 발생했으나 chattingEntity 존재 여부에 대한 조건을 걸고 없을 시 채팅 내역이 없다는 message를 리턴하도록 수정했습니다.
프론트의 요청으로 enterChatRoom에서 recruitId도 리턴 값에 포함되었습니다. 따라서 ChatEnterDto에도 recruitId가 추가되었습니다.
기존에 getRecordPages에서 정렬 방식으로 UpdatedAt에서 registerdAt으로 변경했으나 미처 테스트 코드를 수정하지 못해 이 부분에서 테스트를 통과하지 못했습니다.
따라서 테스트 코드에서도 해당 부분을 변경하여 테스트를 통과함을 확인했습니다.
> Feat: 초대 가능한 리스트 추가
