AnonymousZB14/USports_BE

- src/main/java/com/anonymous/usports/domain/recruit/controller/RecruitController.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitDeleteResponse.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitRegister.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitUpdate.java
- src/main/java/com/anonymous/usports/domain/recruit/entity/RecruitEntity.java
- src/main/java/com/anonymous/usports/domain/recruit/service/RecruitService.java
- src/main/java/com/anonymous/usports/domain/recruit/service/impl/RecruitServiceImpl.java
- src/main/java/com/anonymous/usports/global/constant/ResponseConstant.java
- src/main/java/com/anonymous/usports/global/exception/ErrorCode.java
**AS-IS**
**TO-BE**
운동 모집 게시글 한건 조회, 수정, 삭제구현
- Response 필드가 2개라서 new 이용해서 생성자로 초기화 하도록 변경
> 운동 모집 게시글 CRUD 작성 완료

- src/main/java/com/anonymous/usports/domain/participant/entity/ParticipantEntity.java
- src/main/java/com/anonymous/usports/domain/participant/repository/ParticipantRepository.java
- src/main/java/com/anonymous/usports/domain/participant/service/impl/ParticipantServiceImpl.java
- src/main/java/com/anonymous/usports/domain/recruit/entity/RecruitEntity.java
- src/main/java/com/anonymous/usports/domain/sports/entity/SportsEntity.java
**AS-IS**
**TO-BE**
JpaRepository 인식 안되는것 수정
> Fix: JpaRepository 메서드 명 수정

- src/main/java/com/anonymous/usports/domain/participant/controller/ParticipantController.java
- src/main/java/com/anonymous/usports/domain/participant/dto/ParticipantManage.java
- src/main/java/com/anonymous/usports/domain/participant/dto/ParticipantResponse.java
- src/main/java/com/anonymous/usports/domain/participant/dto/ParticipateResponse.java
- src/main/java/com/anonymous/usports/domain/participant/repository/ParticipantRepository.java
- src/main/java/com/anonymous/usports/domain/participant/service/ParticipantService.java
- src/main/java/com/anonymous/usports/domain/participant/service/impl/ParticipantServiceImpl.java
- src/main/java/com/anonymous/usports/global/constant/ResponseConstant.java
- src/main/java/com/anonymous/usports/global/constant/TokenConstant.java
**AS-IS**
**TO-BE**
중복 신청이 가능했던 것에서 아래 3가지의 상황으로 나눠서 처리
- 정상 참여 신청
- 참여 신청은 되었으나, 아직 수락되지 않았을 때
- 참여 신청이 이미 수락된 상태
(이부분 코드가 뭔가 맘에 안들어서 수정 의견 있으시면 편하게 말씀 주세요!)
> 모집 글 참여 신청 중복되던 것 수정 

- src/main/java/com/anonymous/usports/domain/follow/controller/FollowController.java
- src/main/java/com/anonymous/usports/domain/follow/dto/FollowDto.java
- src/main/java/com/anonymous/usports/domain/follow/dto/FollowListDto.java
- src/main/java/com/anonymous/usports/domain/follow/dto/FollowMemberDetail.java
- src/main/java/com/anonymous/usports/domain/follow/dto/FollowResponse.java
- src/main/java/com/anonymous/usports/domain/follow/entity/FollowEntity.java
- src/main/java/com/anonymous/usports/domain/follow/repository/FollowRepository.java
- src/main/java/com/anonymous/usports/domain/follow/service/FollowService.java
- src/main/java/com/anonymous/usports/domain/follow/service/impl/FollowServiceImpl.java
- src/main/java/com/anonymous/usports/global/constant/ResponseConstant.java
- src/main/java/com/anonymous/usports/global/exception/ErrorCode.java
- src/main/java/com/anonymous/usports/global/exception/FollowException.java
- src/main/java/com/anonymous/usports/global/exception/MyExceptionHandler.java
- src/main/java/com/anonymous/usports/global/type/FollowDecisionType.java
- src/main/java/com/anonymous/usports/global/type/FollowListType.java
- src/main/java/com/anonymous/usports/global/type/FollowStatus.java
**AS-IS**
- follow 신청, 취소
- follow 수락, 거절
- follow 리스트
**TO-BE**
> Feat: follow 신청, 취소, follow 수락, 거절

- src/main/java/com/anonymous/usports/global/exception/ErrorCode.java
- src/main/java/com/anonymous/usports/global/exception/ErrorResponse.java
- src/main/java/com/anonymous/usports/global/exception/MyExceptionHandler.java
**AS-IS**
- 에러 발생 시 Status가 제대로 나오도록 수정했습니다.
**TO-BE**
> Refactor: Exception 관련 Response 수정

- src/main/java/com/anonymous/usports/domain/follow/controller/FollowController.java
**AS-IS**
- getFollowList의 page defaultValue 값 설정
**TO-BE**
> Refactor: getFollowList의 page defaultValue 값 설정

- src/main/java/com/anonymous/usports/domain/record/controller/RecordController.java
**AS-IS**
- Swagger에서 @RequestPart 어노테이션이 붙은 항목이 보이지 않아 @Parameter를 붙였습니다.
**TO-BE**
> Refactor: Record 등록 부분 @Parameter 추가

- src/main/java/com/anonymous/usports/domain/member/dto/MemberUpdate.java
- src/main/java/com/anonymous/usports/domain/member/service/impl/MemberServiceImpl.java
- src/test/java/com/anonymous/usports/domain/member/service/MemberServiceTest.java
**AS-IS**
[MemberServiceImpl]
- 맨토님이 짚어주신 부분 수정
**TO-BE**
> REFACTOR : memberService code refactoring

- src/main/java/com/anonymous/usports/domain/participant/dto/ParticipantDto.java
- src/main/java/com/anonymous/usports/domain/participant/entity/ParticipantEntity.java
- src/main/java/com/anonymous/usports/domain/participant/service/impl/ParticipantServiceImpl.java
- src/main/java/com/anonymous/usports/domain/recruit/controller/RecruitController.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitRegister.java
- src/main/java/com/anonymous/usports/domain/recruit/service/RecruitService.java
- src/main/java/com/anonymous/usports/domain/recruit/service/impl/RecruitServiceImpl.java
- src/main/java/com/anonymous/usports/domain/sportsskill/entity/SportsSkillEntity.java
- src/test/java/com/anonymous/usports/domain/recruit/service/RecruitServiceTest.java
> Fix : PR#48 에서 변경된 부분이 Git merge 오류로 인해 없어진 부분 수정

- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitDto.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitRegister.java
- src/main/java/com/anonymous/usports/global/type/SportsGrade.java
- src/test/java/com/anonymous/usports/domain/recruit/service/RecruitServiceTest.java
POST /recruit 시에 request, response gradeFrom, gradeTo에 대한 type 수정
> Fix : Post /recruit 시에 SportsGrade request, response 값 수정

- src/main/java/com/anonymous/usports/domain/member/service/impl/MemberServiceImpl.java
**AS-IS**
- 불필요한 if문 제거
- 동일 throw 사용하는 catch문 통일
**TO-BE**
> Refactor : 프로필 이미지 관련 리팩토링

- src/main/java/com/anonymous/usports/domain/member/dto/MemberDto.java
- src/main/java/com/anonymous/usports/domain/member/dto/MemberRegister.java
- src/main/java/com/anonymous/usports/domain/member/entity/MemberEntity.java
- src/main/java/com/anonymous/usports/domain/participant/dto/ParticipantDto.java
- src/main/java/com/anonymous/usports/domain/participant/repository/ParticipantRepository.java
- src/main/java/com/anonymous/usports/domain/participant/service/PenaltyScheduler.java
- src/main/java/com/anonymous/usports/domain/profile/service/impl/ProfileServiceImpl.java
- src/main/java/com/anonymous/usports/domain/record/service/impl/RecordServiceImpl.java
- src/main/java/com/anonymous/usports/domain/recruit/service/impl/RecruitServiceImpl.java
- src/main/java/com/anonymous/usports/global/constant/NumberConstant.java
- src/test/java/com/anonymous/usports/test/PenaltySchedulerTest.java
**[Scheduling]**
Scheduling 시간 : 매일 03시
meeting date를 기준 evaluate_at = null인 Participant에 대하여 패널티를 부여한다.
- startDateTime : 75시간 전
- endDateTime : 51시간 전
이 부분을 Paging 처리하여 100개씩 끊어서 Participant에 해당하는 Member에 Penalty를 부여한다. 
- Penalty는 MemberEntity에 penalty_count로 저장된다.
**[Manner 점수 계산]**
- 기존 MannerScore update 시 로직 수정
- penalty 부여 시 mannerScore update 하도록 수정
> 타인 평가 하지 않은 경우 Penalty 부여

- src/main/java/com/anonymous/usports/domain/follow/dto/FollowResponse.java
- src/main/java/com/anonymous/usports/domain/record/controller/RecordController.java
- src/test/java/com/anonymous/usports/domain/follow/service/impl/FollowServiceImplTest.java
**AS-IS**
- FollowResponse에 id를 followId로 변경
- RecordController에 안쓰는 get 메서드 제거
**TO-BE**
> Refactor: 변수명 변경과 불필요한 코드 삭제

- src/main/java/com/anonymous/usports/domain/customerservice/controller/CsController.java
- src/main/java/com/anonymous/usports/domain/customerservice/service/impl/CsServiceImpl.java
- src/main/java/com/anonymous/usports/domain/member/controller/MemberController.java
- src/main/java/com/anonymous/usports/domain/member/dto/MemberUpdate.java
- src/main/java/com/anonymous/usports/websocket/controller/ChatRoomController.java
- src/main/java/com/anonymous/usports/websocket/service/impl/ChatRoomServiceImpl.java
**AS-IS**
[CsController -> CsServiceImpl]
```
if (!StringUtils.hasText(email)) {
email = null;
}
if (!StringUtils.hasText(statusNum)) {
statusNum = null;
}
```
해당 부분 컨트롤러에서 서비스로 옮김 (전에 리팩토링 했던 것이 적용이 안 됨)
[enterChatRoom]
- 컨트롤러에서 주석처리 했던거, 활성화 시킴
[ChatRoomServiceImpl]
- 람다 함수, 간단하게 변경
**TO-BE**
> Refactor : API 업데이트 하면서 리팩토링

- src/main/java/com/anonymous/usports/domain/mypage/dto/MyPageParticipant.java
- src/main/java/com/anonymous/usports/domain/participant/controller/ParticipantController.java
- src/main/java/com/anonymous/usports/domain/recruit/controller/RecruitController.java
- src/main/java/com/anonymous/usports/domain/recruit/dto/RecruitResponse.java
- src/main/java/com/anonymous/usports/domain/recruit/service/impl/RecruitServiceImpl.java
- src/main/java/com/anonymous/usports/global/exception/TypeException.java
- src/main/java/com/anonymous/usports/global/type/Gender.java
- src/main/java/com/anonymous/usports/global/type/SportsGrade.java
**[MyPageParticipant]**
- recruitId 필드 추가
**[Type(enum) 에러]**
- 어떤 필드에서 오류 발생했는지 알 수 있도록 오류메시지 수정
**[GET /recruit/{recruitId} 시 반환 데이터 추가]**
- 해당 모집글이 meetingDate가 지난 경우 참여자의 memberId List 도 함께 반환
> Refactor : FE 요청 사항 적용

- src/main/java/com/anonymous/usports/UsportsApplication.java
> Fix: 서버 timezone 설정

- src/main/java/com/anonymous/usports/domain/record/service/impl/RecordServiceImpl.java
**AS-IS**
[RecordServiceImpl 줄바꿈 개선]
RecordServiceImpl에 줄바꿈을 통해 가독성을 높였습니다.
**TO-BE**
> Refactor: RecordServiceImpl 줄바꿈 개선

- src/main/java/com/anonymous/usports/domain/evaluation/service/impl/EvaluationServiceImpl.java
- src/main/java/com/anonymous/usports/domain/participant/dto/ParticipantListDto.java
- src/main/java/com/anonymous/usports/domain/participant/service/impl/ParticipantServiceImpl.java
- src/main/java/com/anonymous/usports/global/type/ParticipantStatus.java
> Refcator: Participant 관련

- src/main/java/com/anonymous/usports/domain/record/controller/RecordController.java
- src/main/java/com/anonymous/usports/domain/record/dto/RecordDetail.java
- src/main/java/com/anonymous/usports/domain/record/service/RecordService.java
- src/main/java/com/anonymous/usports/domain/record/service/impl/RecordServiceImpl.java
- src/main/java/com/anonymous/usports/domain/recordlike/repository/RecordLikeRepository.java
- src/test/java/com/anonymous/usports/domain/record/service/impl/RecordServiceImplTest.java
- Record 단건 조회 시 로그인 유저가 해당 게시물에 좋아요를 누른 상태인지 여부를 확인할 수 있는데이터 추가
- RecordDetail.currentUserLikes (boolean)
- 테스트 코드 수정
> Refactor : GET /record/{recordId}의 Response에 로그인 유저가 좋아요 누른 상태인지 여부 데이터 추가

- src/main/java/com/anonymous/usports/domain/record/repository/RecordRepository.java
- src/main/java/com/anonymous/usports/domain/record/service/impl/RecordServiceImpl.java
**AS-IS**
**[기록글 리스트 출력 순서 변경]**
기존 updatedAt 내림차순 정렬로 기록 리스트가 출력되던 것을 registeredAt 내림차순으로 변경했습니다.
**TO-BE**
> Refactor: 기록 리스트 정렬 변경

- src/main/java/com/anonymous/usports/domain/recruit/repository/RecruitRepository.java
- src/main/java/com/anonymous/usports/domain/recruit/service/RecruitEndScheduler.java
MeetingDate가 현재 시간 "이전"인 것을 END 처리해야하는데 "이후"를 END 처리하던 것 수정
> Fix : MeetingDate가 현재 시간 "이전"인 것을 END 처리해야하는데 "이후"로 되어있던 것 수정

- src/main/java/com/anonymous/usports/websocket/controller/ChatRoomController.java
- src/main/java/com/anonymous/usports/websocket/dto/ChatResponses/ChatEnterDto.java
- src/main/java/com/anonymous/usports/websocket/dto/ChatResponses/ChatInviteDto.java
- src/main/java/com/anonymous/usports/websocket/dto/ChatResponses/CreateDMDto.java
- src/main/java/com/anonymous/usports/websocket/dto/ChatResponses/CreateRecruitChat.java
- src/main/java/com/anonymous/usports/websocket/repository/ChatPartakeRepository.java
- src/main/java/com/anonymous/usports/websocket/service/ChatRoomService.java
- src/main/java/com/anonymous/usports/websocket/service/impl/ChatRoomServiceImpl.java
- src/test/java/com/anonymous/usports/domain/chatroom/service/ChatRoomServiceImplTest.java
**AS-IS**
[ChatEnter]
응답값 추가
- 채팅방 ID
- 채팅방 이름
- 채팅방에 들어가 있는 유저들의 정보
[Direct Message]
- 1대1 채팅방을 만들 때에 채팅방 ID 응답
[Recruit, invite]
- 모임 채팅방 + 모임 채팅방에 유저 초대하기 응답에 채팅방 ID 추가
> Refactor : new responses

- src/main/java/com/anonymous/usports/domain/record/dto/RecordDto.java
- src/main/java/com/anonymous/usports/domain/record/dto/RecordRegister.java
- src/main/java/com/anonymous/usports/domain/record/entity/RecordEntity.java
- src/main/java/com/anonymous/usports/domain/record/service/impl/RecordServiceImpl.java
**AS-IS**
[문제가 발생해서 thumbnail 부분 삭제했습니다.]
**TO-BE**
> Refactor: thumbnail 부분 삭제

- src/main/java/com/anonymous/usports/domain/notification/controller/NotificationSseController.java
> Fix : SSE send 시 한글 깨짐 문제 수정
